---
- hosts: development
  tasks:
    - name: Configura huso horario
      timezone:
        name: America/Los_Angeles
      become: yes
    - name: Actualiza paquetes del sistema operativo
      apt:
        upgrade: dist
        update_cache: yes
      become: yes
      notify: Reinicia servidor
    - name: Instala cURL
      apt:
        name: "curl"
        state: present
      become: yes
    - name: Instala Docker
      apt:
        name: "docker.io"
        state: present
      become: yes
    - name: Instala exa
      apt:
        name: "exa"
        state: present
      become: yes
    - name: Instala fd
      apt:
        name: "fd-find"
        state: present
      become: yes
    - name: Instala Powerline fonts
      apt:
        name: "fonts-powerline"
        state: present
      become: yes
    - name: Instala Git
      apt:
        name: "git"
        state: present
      become: yes
    - name: Instala Make
      apt:
        name: "make"
        state: present
      become: yes
    - name: Instala Neofetch
      apt:
        name: "neofetch"
        state: present
      become: yes
    - name: Instala Neovim
      apt:
        name: "neovim"
        state: present
      become: yes
    - name: Instala Node Package Manager
      apt:
        name: "npm"
        state: present
      become: yes
    - name: Instala pip
      apt:
        name: "python3-pip"
        state: present
      become: yes
    - name: Instala ripgrep
      apt:
        name: "ripgrep"
        state: present
      become: yes
    - name: Instala tmux
      apt:
        name: "tmux"
        state: present
      become: yes
    - name: Instala ctags
      apt:
        name: "universal-ctags"
        state: present
      become: yes
    - name: Instala Docker SDK para Python
      pip:
        name: docker
      notify: Reinicia servidor
    - name: Instala Powerline shell
      pip:
        name: powerline-shell
    - name: Agrega '{{ ansible_user_id }}' al grupo docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: yes
      notify: Reinicia servidor
    - name: Copia credenciales
      copy:
        src: ~/.vault
        dest: "{{ ansible_facts.user_dir }}"
    - name: Copia claves SSH
      copy:
        src: ~/.ssh/id_rsa
        dest: "{{ ansible_facts.user_dir }}/.ssh/"
  handlers:
    - name: Reinicia servidor
      reboot:
      become: yes

- hosts: development
  tasks:
    - name: Prueba Docker
      docker_container:
        name: hello-world
        image: hello-world
